export default[
    // "html5","css3","js","es6","jquery","vue",'git','小程序','echarts'
    {
        value:'html5',
        textStyle:{
            color:'#f00',
            fontSize:20
        }
    },
    {
        value:'css3',
        textStyle:{
            color:'#f00',
            fontSize:20
        }
    },
    {
        value:'js',
        textStyle:{
            color:'#f00',
            fontSize:20
        }
    },
    {
        value:'es6',
        textStyle:{
            color:'#f00',
            fontSize:20
        }
    },
    {
        value:'jquery',
        textStyle:{
            color:'#f00',
            fontSize:20
        }
    },
    {
        value:'vue',
        textStyle:{
            color:'#f00',
            fontSize:20
        }
    },
    {
        value:'git',
        textStyle:{
            color:'#f00',
            fontSize:20
        }
    },
    {
        value:'小程序',
        textStyle:{
            color:'#f00',
            fontSize:20
        }
    },
    {
        value:'echarts',
        textStyle:{
            color:'#f00',
            fontSize:20
        }
    }
]

